### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by jtlz2** [JohannesBuchner/PyDNest#1]
Hi @JohannesBuchner - very glad to see you've built a bridge for this.... :)

I have DNest3 running OK, but your patch fails with the latest version (commit be5a4231b49771f74a170375e784fc9c18e81274)

Any idea of how much slower your pure python version might be?

Any short term plans to bring this under jbopt?

Thanks as always.

**Comment by jtlz2** [comment]
@JohannesBuchner I applied the patch by hand (libdnest3(s).so was not generated, so I symlinked to the dylib), and now running make in PyDNest/ runs into C++ difficulties (presumably a namespace issue, but I'm not a C++ programmer..):

g++ -fPIC -O2 -Wall -Wextra -ansi -pedantic -I /Users/xxx/src/DNest3/include/ -arch x86_64 -c MyModel.cpp -o MyModel.o
MyModel.cpp:59:12: error: use of undeclared identifier 'cout'; did you mean
      'count'?
        ifverbose cout << "MyModel::constructor. calling allocate" << endl;
                  ^~~~
                  count
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      'count' declared here
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:59:12: error: reference to overloaded function could not be
      resolved; did you mean to call it?
        ifverbose cout << "MyModel::constructor. calling allocate" << endl;
                  ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      possible target for call
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:61:12: error: use of undeclared identifier 'cout'; did you mean
      'count'?
        ifverbose cout << "MyModel::constructor. calling allocate done" << endl;
                  ^~~~
                  count
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      'count' declared here
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:61:12: error: reference to overloaded function could not be
      resolved; did you mean to call it?
        ifverbose cout << "MyModel::constructor. calling allocate done" << endl;
                  ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      possible target for call
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:67:12: error: use of undeclared identifier 'cout'; did you mean
      'count'?
        ifverbose cout << "MyModel::fromPrior. calling fromPrior" << endl;
                  ^~~~
                  count
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      'count' declared here
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:67:12: error: reference to overloaded function could not be
      resolved; did you mean to call it?
        ifverbose cout << "MyModel::fromPrior. calling fromPrior" << endl;
                  ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      possible target for call
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:69:12: error: use of undeclared identifier 'cout'; did you mean
      'count'?
        ifverbose cout << "MyModel::fromPrior. calling fromPrior done" << endl;
                  ^~~~
                  count
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      'count' declared here
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:69:12: error: reference to overloaded function could not be
      resolved; did you mean to call it?
        ifverbose cout << "MyModel::fromPrior. calling fromPrior done" << endl;
                  ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      possible target for call
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:78:12: error: use of undeclared identifier 'cout'; did you mean
      'count'?
        ifverbose cout << "MyModel::perturb. calling perturb" << endl;
                  ^~~~
                  count
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      'count' declared here
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:78:12: error: reference to overloaded function could not be
      resolved; did you mean to call it?
        ifverbose cout << "MyModel::perturb. calling perturb" << endl;
                  ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      possible target for call
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:80:12: error: use of undeclared identifier 'cout'; did you mean
      'count'?
        ifverbose cout << "MyModel::perturb. calling perturb done: " << ...
                  ^~~~
                  count
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      'count' declared here
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:80:12: error: reference to overloaded function could not be
      resolved; did you mean to call it?
        ifverbose cout << "MyModel::perturb. calling perturb done: " << ...
                  ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      possible target for call
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:86:12: error: use of undeclared identifier 'cout'; did you mean
      'count'?
        ifverbose cout << "MyModel::logLikelihood. calling logLikelihood...
                  ^~~~
                  count
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      'count' declared here
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:86:12: error: reference to overloaded function could not be
      resolved; did you mean to call it?
        ifverbose cout << "MyModel::logLikelihood. calling logLikelihood...
                  ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      possible target for call
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:89:12: error: use of undeclared identifier 'cout'; did you mean
      'count'?
        ifverbose cout << "MyModel::logLikelihood. calling logLikelihoo...
                  ^~~~
                  count
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      'count' declared here
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:89:12: error: reference to overloaded function could not be
      resolved; did you mean to call it?
        ifverbose cout << "MyModel::logLikelihood. calling logLikelihoo...
                  ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1083:1: note: 
      possible target for call
count(_InputIterator __first, _InputIterator __last, const _Tp& __value_)
^
MyModel.cpp:95:12: error: use of undeclared identifier 'cout'
        ifverbose cout << "MyModel::print. calling print" << endl;
                  ^
MyModel.cpp:100:12: error: use of undeclared identifier 'cout'
        ifverbose cout << "MyModel::print. calling print done: " << endl;
                  ^
18 errors generated.

**Comment by jtlz2** [comment]
Ahh - fixed by adding

```
#include<iostream>
```

to MyModel.cpp...

**Comment by jtlz2** [comment]
I had to set

```
LIBS = -ldnest3 -lgsl -lgslcblas -lboost_system -lboost_thread-mt
```

in you makefile (i.e. dnest3s -> dnest3; boost_thread -> boost_thread-mt

and on OSX:

```
-soname -> -install_name
```

The library builds OK... now to test it...

**Comment by jtlz2** [comment]
Runs!

**Comment by JohannesBuchner** [comment]
I am curious to hear your experience of the performance of DNest...
Do you think the changes are specific to MacOS or they should be also on e.g. Linux? The #include seems harmless enough.

**Comment by jtlz2** [comment]
I will investigate. I don't know how you got away without the #include before but it's definitely necessary on my setup. All the other changes are I think necessary except the Mac-specific -soname -> -install_name.
