### ISSUE TITLE
MPI?

### ISSUE THREAD

**Issue by jtlz2** [JohannesBuchner/PyDNest#3]
Bearing in mind that I don't fully understand the algorithm, would Py(DNest) gain anything from MPI in the way that (Py)MultiNest does?

**Comment by JohannesBuchner** [comment]
AFAIK, DNest is an intrinsically sequential algorithm, as one MCMC particle is moved around. I think, in principle, something similar to parallel tempering is possible, but has never been tried in the context of DNest. Perhaps Brendon Brewer (@eggplantbren) would be interested if you would to investigate in the direction of parallelisation. Please open a bug in https://github.com/eggplantbren/DNest3.

**Comment by eggplantbren** [comment]
DNest3 is parallelised using boost threads. Each thread evolves its own particles, whose results are periodically pooled.

**Comment by JohannesBuchner** [comment]
And that will probably not work with Python callbacks, because of the GIL.

**Comment by JohannesBuchner** [comment]
Thanks @eggplantbren for helping out in correcting my statement.
